"""Add is_enabled column to users table

Revision ID: 3f0e3382a543
Revises: c98c1b3e1c84
Create Date: 2025-09-12 11:05:15.992967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f0e3382a543'
down_revision = 'c98c1b3e1c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'TERMINATED'),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'TERMINATED'),
               nullable=False)

    # ### end Alembic commands ###
