"""Add request_no to UserRequest

Revision ID: 7bf001d2f68e
Revises: afb1aaa14924
Create Date: 2025-09-10 14:27:29.058535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf001d2f68e'
down_revision = 'afb1aaa14924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_no', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint('uq_request_no', ['request_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('request_no')

    # ### end Alembic commands ###
