"""empty message

Revision ID: 884f60108cc6
Revises: c333e6fecfe3
Create Date: 2025-09-04 17:48:18.860726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884f60108cc6'
down_revision = 'c333e6fecfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.drop_index('email_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.create_index('email_address', ['email_address'], unique=True)

    # ### end Alembic commands ###
