"""Add created_date column to UserRequest

Revision ID: b2c858db071e
Revises: 7bf001d2f68e
Create Date: 2025-09-11 16:07:50.211358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c858db071e'
down_revision = '7bf001d2f68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
